backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: content/uploads
public_folder: /assets/uploads
# logo_url: https://moderncollab.netlify.app/assets/uploads/logo.svg


collections:
  - name: pages
    label: Pages
    delete: false
    editor:
      preview: false
    files:
      - file: content/english.md
        label: English
        name: english
        fields:
          - label: Title
            name: title
            required: true
            widget: string
            hint: ""
            default: ""
          - label: Content
            name: body
            required: true
            widget: markdown
            hint: ""
            default: ""
            buttons:
              - bold
              - italic
              - link
            editorComponents: []
          - label: Form catchphrase
            name: catchphrase
            required: true
            widget: string
            hint: ""
            default: ""
          - label: Email us
            name: emailus
            required: true
            widget: markdown
            buttons:
              - link
      - file: content/french.md
        label: French
        name: french
        fields:
          - label: Title
            name: title
            required: true
            widget: string
            hint: ""
            default: ""
          - label: Content
            name: body
            required: true
            widget: markdown
            hint: ""
            default: ""
            buttons:
              - bold
              - italic
              - link
            editorComponents: []
          - label: Form catchphrase
            name: catchphrase
            required: true
            widget: string
            hint: ""
            default: ""
          - label: Email us
            name: emailus
            required: true
            widget: markdown
            buttons:
              - link
  - name: settings
    label: Settings
    format: json
    delete: false
    editor:
      preview: false
    files:
      - file: content/globals/settings.json
        label: Settings
        name: settings
        fields:
          - label: Site name
            name: name
            required: true
            widget: string
            hint: ""
            default: ""
          - label: Site description
            name: description
            required: true
            widget: string
            hint: ""
            default: ""
          - label: Logo
            name: logo
            required: true
            widget: image
            hint: "Format: svg"
            default: ""
            allow_multiple: false
          - label: SEO image
            name: image
            required: true
            widget: image
            hint: 1200×630px, < 1MB
            default: ""
            allow_multiple: false
          - label: Cookies notice
            name: cookies
            required: false
            widget: markdown
            hint: ""
            default: ""
            buttons:
              - bold
              - link
            editorComponents: []
          - label: Google Tag Manager code
            name: gtm
            required: false
            widget: string
            hint: ""
            default: ""

