module.exports = {
  theme: {
	fontFamily: {
	  body: [
		'Open Sans',
		'-apple-system',
		'BlinkMacSystemFont',
		'"Segoe UI"',
		'Roboto',
		'"Helvetica Neue"',
		'Arial',
		'"Noto Sans"',
		'sans-serif',
		'"Apple Color Emoji"',
		'"Segoe UI Emoji"',
		'"Segoe UI Symbol"',
		'"Noto Color Emoji"',
	  ],
	  display: [
		'Handlee',
		'-apple-system',
		'BlinkMacSystemFont',
		'"Segoe UI"',
		'Roboto',
		'"Helvetica Neue"',
		'Arial',
		'"Noto Sans"',
		'sans-serif',
		'"Apple Color Emoji"',
		'"Segoe UI Emoji"',
		'"Segoe UI Symbol"',
		'"Noto Color Emoji"',
	  ],
	},
	extend: {
	  screens: {
		'xxl': '1440px'
	  },
	  width: {
		'240': '240px',
	  },
	minWidth: {
		'400': '400px',
	},
	minHeight: {
		'400': '400px',
	},
		  zIndex: {
		'2000': '2000',
	  },

	  colors: {

	  }
	},
	//     backgroundColor: theme => theme('colors'),
	//     borderColor: theme => ({
	//         ...theme('colors'),
	//         default: theme('colors.gray.800', 'currentColor'),
	//     }),
	//     boxShadow: {
	//         default: '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)',
	//         md: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
	//         lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
	//         xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
	//         '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
	//         inner: 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
	//         outline: '0 0 0 3px rgba(66, 153, 225, 0.5)',
	//         none: 'none',
	//     },
	//     letterSpacing: {
	//         tighter: '-0.022em',
	//         tight: '-0.019em',
	//         normal: '-0.11em',
	//         wide: '0',
	//         wider: '0.024em',
	//         widest: '0.043em',
	//     },
	//     lineHeight: {
	//         none: '1',
	//         tight: '1.25',
	//         snug: '1.375',
	//         normal: '1.5',
	//         relaxed: '1.625',
	//         loose: '2',
	//     },
	//     listStyleType: {
	//         none: 'none',
	//         disc: 'disc',
	//         decimal: 'decimal',
	//     },
	//     margin: (theme, { negative }) => ({
	//         auto: 'auto',
	//         ...theme('spacing'),
	//         ...negative(theme('spacing')),
	//     }),
	//     maxHeight: {
	//         full: '100%',
	//         screen: '100vh',
	//     },
	//     minHeight: {
	//         '0': '0',
	//         full: '100%',
	//         screen: '100vh',
	//     },
	// },
	//variants: {
	//     accessibility: ['responsive', 'focus'],
	//     alignContent: ['responsive'],
	//     alignItems: ['responsive'],
	//     alignSelf: ['responsive'],
	//     appearance: ['responsive'],
	//     backgroundAttachment: ['responsive'],
	//     backgroundColor: ['responsive', 'hover', 'focus'],
	//     backgroundPosition: ['responsive'],
	//     backgroundRepeat: ['responsive'],
	//     backgroundSize: ['responsive'],
	//     borderCollapse: ['responsive'],
	//     borderColor: ['responsive', 'hover', 'focus'],
	//     borderRadius: ['responsive'],
	//     borderStyle: ['responsive'],
	//     borderWidth: ['responsive'],
	//     boxShadow: ['responsive', 'hover', 'focus'],
	//     cursor: ['responsive'],
	//     display: ['responsive'],
	//     fill: ['responsive'],
	//     flex: ['responsive'],
	//     flexDirection: ['responsive'],
	//     flexGrow: ['responsive'],
	//     flexShrink: ['responsive'],
	//     flexWrap: ['responsive'],
	//     float: ['responsive'],
	//     fontFamily: ['responsive'],
	//     fontSize: ['responsive'],
	//     fontSmoothing: ['responsive'],
	//     fontStyle: ['responsive'],
	//     fontWeight: ['responsive', 'hover', 'focus'],
	//     height: ['responsive'],
	//    inset: ['responsive', 'hover'],
	//     justifyContent: ['responsive'],
	//     letterSpacing: ['responsive'],
	//     lineHeight: ['responsive'],
	//     listStylePosition: ['responsive'],
	//     listStyleType: ['responsive'],
	//    margin: ['responsive', 'odd'],
	//     maxHeight: ['responsive'],
	//     maxWidth: ['responsive'],
	//     minHeight: ['responsive'],
	//     minWidth: ['responsive'],
	//     objectFit: ['responsive'],
	//     objectPosition: ['responsive'],
	//     opacity: ['responsive', 'hover', 'focus'],
	//     order: ['responsive'],
	//     outline: ['responsive', 'focus'],
	//     overflow: ['responsive'],
	//     padding: ['responsive'],
	//     placeholderColor: ['responsive', 'focus'],
	//     pointerEvents: ['responsive'],
	//     position: ['responsive'],
	//     resize: ['responsive'],
	//     stroke: ['responsive'],
	//     tableLayout: ['responsive'],
	//     textAlign: ['responsive'],
	//     textColor: ['responsive', 'hover', 'focus'],
	//     textDecoration: ['responsive', 'hover', 'focus'],
	//     textTransform: ['responsive'],
	//     userSelect: ['responsive'],
	//     verticalAlign: ['responsive'],
	//     visibility: ['responsive'],
	//     whitespace: ['responsive'],
	//     width: ['responsive'],
	//     wordBreak: ['responsive'],
	//     zIndex: ['responsive'],
	//},
  },
  corePlugins: {},
  plugins: [
	require('@tailwindcss/custom-forms')
  ],
}
